# This is a basic workflow to help you get started with Actions

name: Hello Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "damo-maker-patch-4" branch
  push:
    branches: 
      - damo-maker-patch-4
  pull_request:
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  name: DamoJay
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      name: Damo
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello $name!
          echo Actor: ${{ github.actor }}
          echo Committed By:: ${{ github.event.commits[0].author.name }}
  weather:
    runs-on: ubuntu-latest
    env:
      location: '37.8136,144.9631'
      lang: en
      units: au
      exclude: 'minutely,hourly,daily,alerts,flags'
      dark_sky_secret: ${{ secrets.dark_sky }}
    steps: 
      - name: Current Weather
        run: curl -s --url https://api.darksky.net/forecast/$dark_sky_secret/$location?lang=$lang&units=$units&exclude=$exclude

  dump:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "GITHUB_CONTEXT" 


  # This workflow contains a single job called "build"
  pull_requests_only:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo Hi $name.
