name: Hello Actions

on:
  push:
    branches: 
      - master
  pull_request:
    types: [closed]
    
env:
  name:  Damo
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      name: Damian J 
    steps:
    - name: Run a one-line script
      run: |
        echo Hello $name!
        echo Actor: ${{ github.actor }}
        echo Committed By: ${{ github.event.commits[0].author.name }}
  weather:
    runs-on: ubuntu-latest
    env:
      location: '37.8136,144.9631'
      lang: en
      units: aus
      exclude: 'minutely,hourly,daily,alerts,flags'
      open_weather_map_secret: ${{ secrets.open_weather_map }}
    steps: 
      - name: Current Weather
        run: curl -s --url https://api.weathermap.org/forecast/open_weather_map_secret/$location?lang=$lang&units=$units&exclude=$exclude   
  dump:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
        
  pull_request_only:

    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: build 
    steps:
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo Hi, $name.

